development:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: interactor-sample_development
  pool:     5
  username: interactor-sample
  password:
  template: template0

test:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: interactor-sample_test
  pool:     5
  username: interactor-sample
  password:
  template: template0

production:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: interactor-sample_production
  pool:     5
  username: interactor-sample
  password:
  template: template0
